export const styles: { [keys: string]: React.CSSProperties } = {
    necessityBox:{
        width:'60%',
        height:'90vh',
        display:'flex',
        margin:'auto',
        flexDirection:'column',
        justifyContent:'center',
        alignItems:'center',
        transition:'0.2s'
    },
    title:{
        color:'rgb(35,156,80)', 
        fontSize:'3em'
    },
    text:{
        fontSize:'25px'
    }
};
