export const styles: { [keys: string]: React.CSSProperties } = {
    headerComponent:{
        padding:'10px 20px',
        height:'8%',
        display:'flex',
        justifyContent:'space-between',
        alignItems:'center',
    },
    logoBox:{
        display:'flex',
        height:"100%",
        alignItems: 'center',
    },
    img:{
        width:"8%",       
    },
    title:{
        marginTop:'3%',
        fontFamily:"Sixtyfour Convergence, sans-serif",
        color:"#15191d"
    },
    divBotoes:{
        display:'flex',
        justifyContent:'space-between',
        width:'23%'
    },
    botaoContato:{
        cursor:'pointer',
        border:'none',
        background:'none',
        display:'flex',
        alignItems:"center",
        fontSize:'20px',
        fontWeight:'600',
        textDecoration:'underline'
    },
    crateListButton:{
        padding:"10px",
        cursor:'pointer',
        border:'none',
        color:'white',
        borderRadius:'60px',
        background:'black',
        display:'flex',
        alignItems:"center",
        fontSize:'20px',
        fontWeight:'600',
    }
};
