export const styles: { [key: string]: React.CSSProperties } = {
  generalDiv: {
    width: "100%",
    height: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "fixed",
    backgroundColor: "rgba(0, 0, 0, 0.500)",
  },
  insideBox: {
    width: "400px",
    height: "400px",
    backgroundColor: "#027fe9",
    borderRadius: "10px",
  },
  form: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "0px 20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    width: "70%",
    height: "20%",
  },
  label: {
    fontWeight: "700",
    fontSize: "18px",
  },
  input: {
    marginBottom: "10%",
    height: "50%",
    width: "100%",
    border: "solid 1px black",
    borderRadius: "5px",
    padding: "10px",
  },
  buttonSubmit: {
    marginTop: "2%",
    width: "40%",
    height: "10%",
    border: "solid 1px black",
    borderRadius: "5px",
    backgroundColor: "#008000",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
  },
  buttonCancel: {
    marginTop: "5%",
    width: "40%",
    height: "10%",
    border: "solid 1px black",
    borderRadius: "5px",
    backgroundColor: "#FF0000",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
  },
};
