import shoppingImage from "../imgs/shopping.jpg";

export const styles: { [keys: string]: React.CSSProperties } = {
  backGround: {
    margin: "0",
    padding: "0",
    backgroundColor: "rgb(35, 156, 80)",
    backgroundSize: "cover",
    height: "100vh",
    width:'100%',
    display: "flex",
    flexDirection: "column",
  },
  instrucionHome: {
    display: "flex",
    alignItems: "center",
    margin:"auto",
    justifyContent: "center",
  },
  title: {
    color: "rgb(225, 221, 217)",
    fontSize: "3em",
    fontFamily: "Ubuntu, sans-serif",
    fontWeight: "700",
    marginBottom: "0",
  },
  subTitle: {
    color: "rgb(225, 221, 217)",
    fontSize: "2em",
    fontWeight: "500",
    fontFamily: "Ubuntu, sans-serif",
  },
  list: {
    height: "100%",
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    width: "100%",
  },
  alignedButtons: {
    width: "80%",
    padding: "0",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  form: {
    height: "100%",
    width: '100%',
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    height: "20%",
    width: '80%',
  },
  label: {
    fontWeight: "700",
    fontSize: "18px",
  },
  input: {
    marginBottom: "10%",
    height: "50%",
    border: "solid 1px black",
    borderRadius: "5px",
    padding: "10px",
  },
  buttonSubmit: {
    marginTop: "2%",
    width: "40%",
    height: "10%",
    border: "solid 1px black",
    borderRadius: "5px",
    backgroundColor: "#008000",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
  },
  buttonCancel: {
    marginTop: "5%",
    width: "40%",
    height: "10%",
    border: "solid 1px black",
    borderRadius: "5px",
    backgroundColor: "#FF0000",
    color: "white",
    fontSize: "20px",
    cursor: "pointer",
  },
};
